# Generated by Django 4.1.2 on 2023-06-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
